version: '2'
services:
  # PostgreSQL database
  db:
    image: postgres:9.5
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  sut:
    build: .
    command: python manage.py test -v3 --noinput
    environment:
      - SETTINGS_CONFIGURATION=local
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_HOSTNAME=db
      - DB_PASSWORD=postgres
    depends_on:
      - db
    volumes:
      - .:/code

